---
title: "Evidence of a map sense: elephant seals account for time and space during long-distance migrations"
author:
  - Roxanne S. Beltran:
      email: roxanne@ucsc.edu
      institute: [UCSC]
      correspondence: true
  - Alexander L. Yuen:
      institute: [UCSC]
      correspondence: false
  - Richard Condit:
      institute: [UCSC]
      correspondence: false
  - Patrick W. Robinson:
      institute: [UCSC]
      correspondence: false
  - Max F. Czapanskiy:
      institute: [HMS]
      correspondence: false
  - Daniel E. Crocker:
      institute: [SSU]
      correspondence: false
  - Daniel P. Costa:
      institute: [UCSC]
      correspondence: false
institute:
  - UCSC: "University of California Santa Cruz, Department of Ecology and Evolutionary Biology, 1156 High Street, Santa Cruz, CA 95064, USA"
  - HMS: "Stanford University, Hopkins Marine Station, 120 Ocean View Blvd, Pacific Grove, CA 93950, USA"
  - SSU: "Sonoma State University, Department of Biology, 1801 East Cotati Ave, Rohnert Park, CA 94928, USA"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::word_document2:
      fig_caption: yes
      reference_docx: "../templates/template.docx" 
      number_sections: false
      pandoc_args:
      - --lua-filter=../templates/scholarly-metadata.lua
      - --lua-filter=../templates/author-info-blocks.lua
      - --lua-filter=../templates/pagebreak.lua
bibliography: references.bib
csl: "../templates/current-biology.csl" 
keywords: |
  Movement ecology, turnaround, return trip, northern elephant seal
---

<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

<!-- With the following code you can access and display values from the yml header above. -->

Keywords: `r rmarkdown::metadata$keywords`

eTOC blurb: Using satellite trackers attached to migrating elephant seals, Beltran et al. discovered that seals know their distance from the breeding beach and allocate extra time to get back if they have farther to travel. These findings provide insight into the astonishing navigational feats and synchronized reproductive schedules of open ocean migrators.

<!-- The following code chunk defines some general settings how code chunks should behave. -->

```{r setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/",
  dpi = 300
)
```

<!-- The actual document text starts here: -->

Many marine animals migrate between foraging areas and reproductive sites, often timing the return migration with extreme precision. In theory, the decision to return should reflect energy acquisition at foraging areas, energetic costs associated with transit, and reaching the reproductive site within a time window appropriate for reproducing. For long-distance migrations to be successful, animals must integrate "map" information to assess where they are relative to their reproductive site as well as "calendar" information to know when to initiate the return migration given their distance from home [@putman2021]. Elephant seals, *Mirounga angustirostris*, migrate thousands of kilometers from reproductive sites to open ocean foraging areas (Figure 1A) yet return within a narrow window of time to specific beaches [@conditMMS]. Each year, pregnant female elephant seals undertake a \~240-day, 10,000 km foraging migration across the Northeast Pacific Ocean before returning to their breeding beaches, where they give birth 5 days after arriving [@conditMMS]. A first step in understanding the navigational abilities required to complete the migration on time is determining whether elephant seals have a map sense (i.e., whether they strategically begin the inbound migration based on how far they need to travel). Using satellite tracking data collected from adult female seals (N=126 tracks from N=108 individuals, 2004-2015), we determined the date on which each seal started its return migration, defined as the date after which daily displacements were consistently toward the breeding beach [@robinson2012] (Figure 1A, Figure S1). Turnaround dates depended strongly on distance from the breeding beach but were unrelated to body condition determined by vertical velocity during drift dives. Seals that foraged farther began their inbound migration earlier. These data provide evidence that seals know their distance from the breeding beach and allocate extra time to get back if they have farther to travel. The ability of seals to adjust the timing of their return migration based on the perception of space and time further elucidates the mechanisms behind their astonishing navigational feats [@robinson2012]. It also provides an understanding of how population-level reproductive synchrony is possible for migratory animals.

Elephant seals return to the same beaches year after year with minimal variation in migration arrival and departure date across individuals (Figure 1B). However, this consistency is not a result of group travel or active coordination because seals forage independently, and it is unknown which cue causes female elephant seals to begin their return migration months prior to giving birth at the breeding beach [@conditMMS]. The animals have vast distributions at sea, across longitudes and latitudes with dramatically different celestial cues and daylengths [@beltran2021] yet return to their beaches a few days before birth. Our objective was to determine the intrinsic and extrinsic factors that motivate foraging elephant seals to turn around and begin directed travel back to their breeding beaches. We predicted that the seals that traveled the farthest would initiate their return the earliest, to allow sufficient time for travel back to the breeding site. Alternatively, we hypothesized that seals would initiate their return after they attained sufficient energy stores for the return home and the subsequent reproductive event. Because elephant seals do not feed while nursing, they must derive all energy needed for lactation from fat reserves gained on the long foraging migration.

We calculated migration departure and arrival dates using satellite tags and time-depth recorders (Figure 1C) [@robinson2012]. Distance from the Año Nuevo breeding beach was averaged every day for each seal and the first derivative of that distance calculated as the daily change, positive or negative (See supplemental experimental procedures). The initiation of the return migration was defined as the last date on which the derivative fell below zero (i.e., the movement was directed toward the breeding beach until the end of the migration). After the migration, each seal was monitored so the birthdate of the pup could be determined. Using drift rate from time-depth recorders as a proxy for body condition, we identified the date at which each seal’s buoyancy switched from negative (e.g., leaner) to positive (e.g., fatter) (Figure S1).

Pupping dates were January 20 ± 7 days, meaning that seals began their return migration ~98 days before giving birth (Figure 1B). Seals started their return migrations when they were 2,814 ± 1,129 km from the breeding beach (Figure 1A). Turnaround distance (p \< 0.0001) but not buoyancy change date (p = 0.60) had significant partial effects in the full model ($R^2_{conditional}$ = 0.80). Seals that did not travel as far had later turnaround dates than farther traveling seals (TurnaroundDate = -0.027 \* TurnaroundDistance -21.91, Figure 1D). 

Despite extensive research into how migratory animals pursue foraging patches in terrestrial [@aikens2017] and marine [@abrahms2019] ecosystems, there has been substantial uncertainty in the when and why of movement decisions made by wild animals. We found that elephant seals show a great deal of variability in when and where they begin their multi-week return migration (Figure 1B) based on their real-time distance from the breeding beach. While the sensory basis of elephant seals’ ability to assess their position (e.g., geomagnetic, celestial, acoustic, or olfactory) remains unknown, our data suggest that elephant seals have a map sense, which allows them to adjust their movement based on their current position relative to their destination [@putman2020]. This may help explain how elephant seals return to the breeding beach just before giving birth despite a maximum transit speed of \~150 km/day. Discovering movement decisions in this species can help us better understand the annual cycle [@mcnamara2007] and explore parallels with other long-distance migrants, including seabirds and whales, with implications for resource management, population connectivity, nutrient flow, species interactions, ecosystem control, and disease dynamics [@lohmann2018; @hussey2015]. 

**Figure 1**: During 10,000km roundtrip migrations, elephant seals (inset) schedule their return to the breeding beach based on their distance. (**A**) Turnaround locations for each elephant seal in yellow overlayed onto the full migration tracks (grey lines). The breeding beach at Año Nuevo Reserve is a black square. (**B, C**) Departure and arrival dates are highly constrained across individuals, while turnaround dates are variable. (**D**) There is a strong correspondence between the distance and date at which seals began their return to the breeding beach such that closer seals turned around later. This staggered turnaround allowed for population-level synchrony for the breeding season. (**E**) There was no relationship between the day seals became positively buoyant and the day seals turned around, suggesting that the attainment of sufficient fat stores does not trigger the return to the breeding colony.

# Acknowledgements

The authors thank A. Marm Kilpatrick and Bruce Lyon for valuable discussions. This research was completed at the University of California Natural Reserve System's Año Nuevo Reserve and was approved by the University of California Santa Cruz Institutional Animal Care and Use Committee \#Costd1709 and the National Marine Fisheries Service marine mammal research permit \#19108. The work was funded by ONR N00014-18-1-2822 (to DPC), the E&P Sound and Marine Life Joint Industry Project of the International Association of Oil and Gas Producers (to DPC), and National Science Foundation award \#2052497 (to RSB and DPC).

# Declaration of Interests

The authors declare no competing interests.

# Author Contributions

RSB, ALY, DPC, PWR conceptualized the manuscript. RSB, RC, MFC, DEC, ALY, PWR, DPC undertook the data curation and formal analysis. RSB, ALY wrote the original draft. RSB, MFC created the data visualizations. DPC, RSB acquired the funding. All authors reviewed and edited the manuscript. 

<!-- The following line inserts a page break  -->

\newpage

# References

<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->

::: {#refs}
:::

\newpage
